/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kripto;

import java.util.Iterator;
import java.util.stream.IntStream;

/**
 *
 * @author Radif
 */
public class form extends javax.swing.JFrame {
    
    private String alpha = "abcdefghijklmnopqrstuvwxyz";
          String encrypted = "";
          String decrypted = "";
          int block = 2;
          String ivparameter = "cbc";
          
          String reverseAlpha = "";
    /**
     * Creates new form form
     */
    public form() {
        
        initComponents();
        setLocationRelativeTo(this);
    }
    
     private String Cleaning_text(String text){
         text = text.replaceAll("\n", "");          
        for(int x = 0; x < text.length(); x++)
        {
            int position = alpha.indexOf(text.charAt(x));
            if (position == -1)
            {
                text= text.replace(text.charAt(x), ' ');
            }
        }        
        return text;
    } 
     
        private static int[] Alphabet;
	static class MyIntStream {
            
		public IntStream stream;
		public MyIntStream() {
			stream = IntStream.range(0, 0);
		}
		
		public MyIntStream concat(IntStream s) {
			this.stream = IntStream.concat(this.stream, s);
			return this;
		}
		
		public MyIntStream concat(int[] s) {
			return this.concat(IntStream.of(s));
		}
	}	
	
	static class Array {
            public static int indexOf(int[] array, int value) {
		int result = -1;
		for (int i = 0; i < array.length; i++) {
		if (array[i] == value) {
		result = i;
		break;
            }
	}
	return result;
    }
}  
   
        
     //VIGENER
//     public  String Encrypt(String text,String key)
//    {
//      String cleaned_text = Cleaning_text(text);
//      String encrypted = "";
//      
//      for(int t = 0,k= 0; t < cleaned_text.length(); t++,k= (k+1) % key.length()){
//       int position = (table.indexOf(cleaned_text.charAt(t)) + table.indexOf(key.charAt(k))) % table.length();
//       encrypted += table.charAt(position );
//      }
//      return encrypted;
       
//    public String Decrypt(String text,String key  ){
//        
//      String cleaned_text = Cleaning_text(text);  
//      String decrypted = "";
//
//      for(int t = 0, k = 0; t < cleaned_text.length(); t++,k= (k+1) % key .length()){
//          
//       int position = (table.indexOf(cleaned_text.charAt(t)) - table.indexOf(key.charAt(k)));
//       position = (position < 0)?(position + table.length()): position;
//       decrypted += table.charAt(position);
//       }
//      return decrypted;
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        enkrip_cbc = new javax.swing.JButton();
        deskrip_cbc = new javax.swing.JButton();
        txtplain = new javax.swing.JTextField();
        txtkey = new javax.swing.JTextField();
        txthasil = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        enkrip_atbash = new javax.swing.JButton();
        dekrip_atbash = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btn_exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Viner Hand ITC", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CBC - ATBASH");

        enkrip_cbc.setText("Enkripsi");
        enkrip_cbc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enkrip_cbcActionPerformed(evt);
            }
        });

        deskrip_cbc.setText("Deskripsi");
        deskrip_cbc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deskrip_cbcActionPerformed(evt);
            }
        });

        txtplain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtplainActionPerformed(evt);
            }
        });

        txtkey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkeyActionPerformed(evt);
            }
        });

        txthasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthasilActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        jLabel2.setText("Plainteks");

        jLabel3.setFont(new java.awt.Font("Orator Std", 0, 12)); // NOI18N
        jLabel3.setText("KEY");

        jLabel4.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("CBC");

        enkrip_atbash.setText("Enkripsi");
        enkrip_atbash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enkrip_atbashActionPerformed(evt);
            }
        });

        dekrip_atbash.setText("Deskripsi");
        dekrip_atbash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dekrip_atbashActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("ATBASH");

        btn_exit.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 1, 14)); // NOI18N
        btn_exit.setText("EXIT");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(379, 379, 379)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enkrip_cbc, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deskrip_cbc, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtplain)
                            .addComponent(txthasil, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                            .addComponent(txtkey)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(enkrip_atbash, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dekrip_atbash, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5)))
                .addGap(61, 61, 61))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(73, 229, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(207, 207, 207))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_exit)
                        .addGap(70, 70, 70))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(enkrip_cbc, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(enkrip_atbash, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deskrip_cbc, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(dekrip_atbash, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtplain, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(3, 3, 3)
                        .addComponent(txtkey, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txthasil, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(btn_exit)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enkrip_cbcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enkrip_cbcActionPerformed
        // TODO add your handling code here:
        int t=0;
        int k = 0;
        int tblock = 0;
        char[] temp = new char[block];
        String text = txtplain.getText();
        String key = txtkey.getText();
        String cleaned_text = Cleaning_text(text);
        encrypted = "";
        
       
        while(t <= cleaned_text.length()){
            if ((t+block)>cleaned_text.length()) {
                tblock = cleaned_text.length()-t;
            }
            else{
                tblock = block;
            }
            if(t==0){
                for (int i=0; i<tblock; i++) {
                    temp[i]= (char) (cleaned_text.charAt(i) ^ ivparameter.charAt(i));
                }
            }
            else{
                for (int i=0; i<tblock; i++) {
                    temp[i]= (char) (cleaned_text.charAt(t+i) ^ encrypted.charAt(t-(tblock-i)));
                }
            }
            for (int i=0; i<tblock; i++) {
                encrypted +=(char) (temp[i] ^ key.charAt(k)) ;
                k= (k+1) % key .length();
            }
            t = t+block;   
        }
        txthasil.setText(encrypted);
    }//GEN-LAST:event_enkrip_cbcActionPerformed

    private void deskrip_cbcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deskrip_cbcActionPerformed
        // TODO add your handling code here:
        int t=0;
        int k = 0;
        int tblock = 0;
        char[] temp = new char[block];
        String key = txtkey.getText();
        decrypted = "";
        
        while(t <= encrypted.length()){
            if ((t+block)>encrypted.length()) {
                tblock = encrypted.length()-t;
            }
            else{
                tblock = block;
            }
            for (int i=0; i<tblock; i++) {
                temp[i]=(char) (encrypted.charAt(t+i) ^ key.charAt(k)) ;
                k= (k+1) % key .length();
            }
            
            if(t==0){
                for (int i=0; i<tblock; i++) {
                    decrypted += (char) (temp[i] ^ ivparameter.charAt(i));  
                }
            }
            else{
                for (int i=0; i<tblock; i++) {
                    decrypted += (char) (temp[i] ^ encrypted.charAt(t-(tblock-i)));
                }
            } 
            t = t+block; 
        }
        txthasil.setText(decrypted);
    }//GEN-LAST:event_deskrip_cbcActionPerformed

    private void txtplainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtplainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtplainActionPerformed

    private void txtkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkeyActionPerformed

    private void txthasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthasilActionPerformed

    private void enkrip_atbashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enkrip_atbashActionPerformed
        // TODO add your handling code here:
        //VIGENERE
        //String key;
//        key = txtkey.getText();
//
//        String res = "";
//        for (int i = 0,j = 0; i < bFile.length; i++) {
//{  
//        
//        int c = bFile[i];
//            if (c < -128 || c > 127)
//                  continue;
//            res += (int) ((c + key.charAt(j) - 128) % 26 );
//            j = ++j % key.length();
//            
//            bFile[i]= (byte) (bFile[i] + key.length()) ;
//}  
//       txtkey.setText("");
//}
//        String text = txtplain.getText();
//        String key = txtkey.getText();
//        txthasil.setText(Encrypt(text,key ));
         
     Alphabet =     new MyIntStream()
                    .concat(IntStream.range('a', 'z' + 1))
                    .concat(IntStream.range('A', 'Z' + 1))
                    .concat(
                    new int[] {' ', '?', '!', '.', ':', '-', '_', '(', ')'}
                    )
                    .stream
                    .toArray();
     
     
     String cleaned_text = Cleaning_text(text);
     encrypted = "";
     
		for (int c : cleaned_text.toCharArray()) {
			
			int idx = Array.indexOf(Alphabet, c);
			
			encrypted += (char)Alphabet[Alphabet.length - 1 - idx];
		}
     String text = txtplain.getText();
     txthasil.setText(Encrypt(text,key ));
    }//GEN-LAST:event_enkrip_atbashActionPerformed

    private void dekrip_atbashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dekrip_atbashActionPerformed
        // TODO add your handling code here:
        //  vigenere
//        String key;
//        key = txtkey.getText();
//        String res = "";
//        for (int i = 0,j = 0; i < bFile.length; i++) {
//{  
//        
//        int c = bFile[i];
//            if (c < -128 || c > 127)
//                  continue;
//            res += (int) ((c - key.charAt(j) + 128) % 26);
//            j = ++j % key.length();
//        bFile[i]= (byte) (bFile[i] - key.length()  ) ;
//        
//  }   
//}
//        String text = txtplain.getText();
//        String key = txtkey.getText();
//        txthasil.setText(Decrypt(text,key ));
        
        String text = txtplain.getText();
       encrypted = "";
		
		for (int c : text.toCharArray()) {
			
			int idx = Array.indexOf(Alphabet, c);
			
			encrypted += (char)Alphabet[Alphabet.length - 1 - idx];
		}	
		
    }//GEN-LAST:event_dekrip_atbashActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        // TODO add your handling code here:
         System.exit(1);
    }//GEN-LAST:event_btn_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton dekrip_atbash;
    private javax.swing.JButton deskrip_cbc;
    private javax.swing.JButton enkrip_atbash;
    private javax.swing.JButton enkrip_cbc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txthasil;
    private javax.swing.JTextField txtkey;
    private javax.swing.JTextField txtplain;
    // End of variables declaration//GEN-END:variables
}
